apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: harbor.h2o-2-19274.h2o.vmware.com/library/solar-system:26
        name: solar-system
      imagePullSecrets:
      - name: regcred
        ports: 
        - containerPort: 80
