apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaDJvLTItMTkyNzQuaDJvLnZtd2FyZS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiaGFyYm9yIiwiYXV0aCI6IllXUnRhVzQ2YUdGeVltOXkifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
